
#define FALSE 0
#define TRUE 1

#define WINDOW_WIDTH 1000
#define WINDOW_HEIGHT 600
#define PADDING 8
#define HEADER 80
#define GAME_WIDTH (WINDOW_WIDTH - (2 * PADDING))
#define GAME_HEIGHT (WINDOW_HEIGHT - HEADER - (2 * PADDING))
#define GAME_WIDTH_START (PADDING + 1 )
#define GAME_WIDTH_END   (PADDING + GAME_WIDTH - 1)
#define GAME_HEIGHT_START (PADDING + HEADER + 1)
#define GAME_HEIGHT_END   (PADDING + HEADER + GAME_HEIGHT + 1 - PADDING)

#define FPS 30
#define FRAME_TARGET_TIME (1000 / FPS)

#define DIRECTION_VERTICAL_UP      0
#define DIRECTION_VERTICAL_DOWN    1
#define DIRECTION_HORIZONTAL_LEFT  2
#define DIRECTION_HORIZONTAL_RIGHT 3

