
#define FALSE 0
#define TRUE 1

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600

#define FPS 30
#define FRAME_TARGET_TIME (1000 / FPS)

#define DIRECTION_VERTICAL_UP      0
#define DIRECTION_VERTICAL_DOWN    1
#define DIRECTION_HORIZONTAL_LEFT  2
#define DIRECTION_HORIZONTAL_RIGHT 3

